---
PLAINTEXT_VARIABLES:
    AWS_REGION: us-east-1
    LOCATIONS_API_URL: https://qa-refinery.nypl.org/api/nypl/locations/v1.0/locations
    KINESIS_BATCH_SIZE: 500
    LOG_LEVEL: info
    MODE: LOCATION_HOURS
    LOCATION_HOURS_SCHEMA_URL: https://qa-platform.nypl.org/api/v0.1/current-schemas/LocationHours
    REDSHIFT_DB_NAME: dev
    REDSHIFT_TABLE: location_hours_dev
ENCRYPTED_VARIABLES:
    KINESIS_STREAM_ARN: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAKAwgZ0GCSqGSIb3DQEHBqCBjzCBjAIBADCBhgYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAwTPhb4zsiMDMbP/Y8CARCAWXD1uGuY+nPfjeE2t8Jp6wPVq86QB5ymIiZjCNZVb1F1eP6MSx5239l7TFJpXvhGJzu52tOSmUbn5q2BqiGiyn0Ck+94hhOJ53G0V2Uk1D/u+PhHkqrxbHKK
    REDSHIFT_DB_HOST: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAKIwgZ8GCSqGSIb3DQEHBqCBkTCBjgIBADCBiAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAzfC7it2NYa1YnFy+4CARCAW1NrqGfSfPptEF4epEXl8Hr6ntrJcZ0DE1GeGt2c2mMnMt7hcim39NTgxHvi5DIldF4J2UJzgG0KBs5UGRU9dyjrQu5zLfdB8Kv50d1lHfvqM2aDQAK0SQ188BY=
    REDSHIFT_DB_USER: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHMwcQYJKoZIhvcNAQcGoGQwYgIBADBdBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDC8BWmZkNuIiBd+zxwIBEIAwb+1L4oqHLpacTC09H1Rn0he/ZlW1iQvH0ES1v9J8mk29bux/RhjCLO44assvSDG1
    REDSHIFT_DB_PASSWORD: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHEwbwYJKoZIhvcNAQcGoGIwYAIBADBbBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDHe+zzEql8Er02e0eQIBEIAud9GTORlsHlAlQlm2H7aannlpHcoswwIwD799JoVBs7H52rWv81S04VwZRVhs/w==
...
