---
PLAINTEXT_VARIABLES:
    AWS_REGION: us-east-1
    LOCATIONS_API_URL: https://qa-refinery.nypl.org/api/nypl/locations/v1.0/locations
    KINESIS_BATCH_SIZE: 500
    LOG_LEVEL: info
    MODE: LOCATION_CLOSURE_ALERTS
    LOCATION_CLOSURE_ALERT_SCHEMA_URL: https://qa-platform.nypl.org/api/v0.1/current-schemas/LocationClosureAlert
ENCRYPTED_VARIABLES:
    KINESIS_STREAM_ARN: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAKcwgaQGCSqGSIb3DQEHBqCBljCBkwIBADCBjQYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAzGKFKfkhNL/mp0vmsCARCAYPb1KOF9VMa/WH4PornMlCpC7xqrAcyANmNAZJ/GaCP7vTXWTQcUAgbub5g5YnP0SWaFE/Xck6I0M/y79CRtG+1ezr/HBpGxqLWhmSJgyLjdC/NwBF1uESpKNat5sz1zsg==
...